export const products = [
    {
        id: 1,
        name: "Hilsha Herring",
        shortDescription: "Premium quality Hilsha Herring",
        longDescription: "Sourced from the Bay of Bengal, our Hilsha Herring is known for its rich taste and freshness.",
        price: 12.99,
        weight: "500g",
        reviews: [
            { user: "Customer1", rating: 4.5, comment: "Delicious and fresh!" },
            { user: "Customer2", rating: 5, comment: "Best Hilsha I've ever had!" },
        ],
        pictures: ["/images/shrimp.png"],
        category: "Saltwater",
    },
    {
        id: 2,
        name: "Pangasius Fillet",
        shortDescription: "Boneless Pangasius Fillet",
        longDescription: "Our Pangasius Fillet is boneless, skinless, and ready to cook. Sustainably sourced from Bangladeshi waters.",
        price: 8.99,
        weight: "400g",
        reviews: [
            { user: "Customer3", rating: 4, comment: "Great value for money!" },
            { user: "Customer4", rating: 4.2, comment: "Tastes really good!" },
        ],
        pictures: ["/images/shrimp.png"],
        category: "Freshwater",
    },
    {
        id: 3,
        name: "Rohu Steaks",
        shortDescription: "Fresh Rohu Fish Steaks",
        longDescription: "Indulge in the succulence of Rohu fish with our carefully cut and frozen Rohu Steaks.",
        price: 9.99,
        weight: "600g",
        reviews: [
            { user: "Customer5", rating: 4.7, comment: "Excellent quality steaks!" },
            { user: "Customer6", rating: 5, comment: "Perfect for grilling!" },
        ],
        pictures: ["/images/shrimp.png"],
        category: "Freshwater",
    },
    {
        id: 4,
        name: "Bangladeshi Shrimp",
        shortDescription: "Premium Bangladeshi Black Tiger Shrimp",
        longDescription: "Harvested from the pristine waters of Bangladesh, our Black Tiger Shrimp promises a taste of the sea like no other.",
        price: 14.99,
        weight: "750g",
        reviews: [
            { user: "Customer7", rating: 4.8, comment: "Sweet and juicy shrimp!" },
            { user: "Customer8", rating: 4.5, comment: "Great for seafood lovers!" },
        ],
        pictures: ["/images/shrimp.png"],
        category: "Saltwater",
    },
    {
        id: 5,
        name: "Pabda Fish Fillet",
        shortDescription: "Tender Pabda Fish Fillet",
        longDescription: "Experience the delicate flavor of Pabda fish with our boneless and skinless Pabda Fish Fillet.",
        price: 11.99,
        weight: "500g",
        reviews: [
            { user: "Customer9", rating: 4.3, comment: "Impressive quality fillets!" },
            { user: "Customer10", rating: 4.6, comment: "Perfect for a quick meal!" },
        ],
        pictures: ["/images/shrimp.png"],
        category: "Freshwater",
    },
];

